name: .NET Build-Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    # note: changing build/name breaks the branch protection
    name: Build-Test

    runs-on: windows-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    
    - name: Restore NuGet Packages
      run: nuget restore
    
    - name: Build
      run: msbuild -t:rebuild -verbosity:diag -property:Configuration=Release
    
    # https://github.com/microsoft/vstest/issues/1663
    - name: Test
      run: vstest.console.exe tests/**.Tests/**/*.Tests.dll
