name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONFIG: Release
  RELEASE_TAG: "v0.0.0"
  RELEASE_VERSION: "0.0.0"
  SOLUTION: Lussatite.FeatureManagement.sln

jobs:

  build:
    # note: changing build/name breaks the branch protection
    name: Build-Test

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    # https://stackoverflow.com/a/58178121
    # https://stackoverflow.com/a/59284102
    # echo "action_state=yellow" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    - name: Get Release Version / Build Variables (Windows)
      run: |
        echo "CONFIG=${{ env.CONFIG }}"
        echo "GITHUB_REF=$env:GITHUB_REF"
        echo "GITHUB_REF_NAME=$env:GITHUB_REF_NAME"
        echo "GITHUB_SHA=$env:GITHUB_SHA"
        echo "RELEASE_TAG=${env:GITHUB_REF##*/}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "RELEASE_TAG=$env:RELEASE_TAG / env.RELEASE_TAG=${{ env.RELEASE_TAG }}"
        echo "RELEASE_VERSION=${env:GITHUB_REF##*/v}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "RELEASE_VERSION=$env:RELEASE_VERSION / env.RELEASE_VERSION=${{ env.RELEASE_VERSION }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
         3.1.x
         6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet Packages
      run: nuget restore

    - name: Build
      run: msbuild -t:rebuild -verbosity:normal -property:Configuration=${{ env.CONFIG }}

    # vstest wildcards: https://github.com/microsoft/vstest/issues/1663
    # run: vstest.console.exe tests/**.Tests/**/*.Tests.dll
    - name: .NET Framework Tests
      run: vstest.console.exe tests.Framework/**.Tests/**/*.Tests.dll

    # dotnet tests for the .NET Core 3.1 / .NET 6 xUnit Test projects
    # dotnet test command does not support wildcards and gets confused by the .NET Framework test projects

    - name: .NET Tests (NetCore31.Tests)
      run: dotnet test tests/Lussatite.FeatureManagement.NetCore31.Tests/Lussatite.FeatureManagement.NetCore31.Tests.csproj --configuration ${{ env.CONFIG }}

    - name: .NET Tests (Net6.Tests)
      run: dotnet test tests/Lussatite.FeatureManagement.Net6.Tests/Lussatite.FeatureManagement.Net6.Tests.csproj --configuration ${{ env.CONFIG }}

    - name: .NET Tests (SessionManagers.Configuration.Tests)
      run: dotnet test tests/Lussatite.FeatureManagement.SessionManagers.Configuration.Tests/Lussatite.FeatureManagement.SessionManagers.Configuration.Tests.csproj --configuration ${{ env.CONFIG }}

    - name: dotnet publish
      #working-directory: ./src/${{ env.PROJECT }}
      run: >
        dotnet publish ${{ env.SOLUTION }}
        --configuration ${{ env.CONFIG }} 
        /p:Version="${{ env.RELEASE_VERSION }}"
        /p:InformationalVersion="${{ env.RELEASE_VERSION }}"
